<?php

/**
 * Implements hook_permission().
 */
function convio_api_permission() {

  return array(
    'administer convio api settings' => array(
      'title' => t('Administer Convio API Settings'),
      'description' => t('Set up the parameters for using the Convio API.'),
    ),
  );

}

/**
 * Implements hook_menu().
 */
function convio_api_menu() {
  $items = array();
  
  $items['admin/config/system/convio_api_config'] = array(
    'title' => 'Convio API Configuration',
    'description' => 'Manage settings to connect with the Convio API',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('convio_api_admin_site_settings'),
    'access arguments' => array('administer convio api settings'),
    'file' => 'include/convio_api.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/config/system/convio_api_test'] = array(
    'title' => 'Convio API Connection Test',
    'description' => 'Test the connection to the Convio Site',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('convio_api_admin_site_test'),
    'access arguments' => array('administer convio api settings'),
    'file' => 'include/convio_api.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  
  return $items;
}

/**
 * Execute request to Convio API
 *
 * @return 
 * Return the response that is generated.
 */
function convio_api_request($api, $method, $params) {
  try {
    $convio_api = new ConvioAPI($api, $method, $params);
    return $convio_api->execute();
  }
  catch (Exception $e) {
    watchdog('convio_api', $e->getMessage(), array(), WATCHDOG_ERROR);
  } 
}

function convio_api_isEmailValid_request($email) {
  $params = array(
    'email' => $email,
    'method' => 'isEmailValid',
  );
  return convio_api_request('constituent', 'server', $params);
}

function convio_api_createOrUpdate_request($email) {
  $params = array(
    'email' => $email,
    'method' => 'createOrUpdate',
  );

  $api_response = convio_api_request('constituent', 'server', $params);

//    return array(
//      "message" => $data['message'],
//      "cons_id" => $data['cons_id'],
//    );
}